name: Analyze a Graph from Twitter
on:
  schedule:
  - cron: '30 * * * *'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Graph Classifier
      uses: actions/checkout@v2
      with:
        repository: johnpierson/DynamoGraphClassifier
    - name: Install .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.100' 
    - name: Run Tweet
      env:
         sig_file_path: ${{ secrets.SIG_FILE_PATH }}  
         twitter_consumer_key: ${{ secrets.TWITTER_CONSUMER_API_KEY }}
         twitter_consumer_secret: ${{ secrets.TWITTER_CONSUMER_API_SECRET }}
         twitter_access_token: ${{ secrets.TWITTER_ACCESS_TOKEN }}
         twitter_access_token_secret: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}  
      run: dotnet run -c Release
